### ISSUE TITLE
Some interactions not working when map contains WebGLPointsLayer with hit detection disabled

### ISSUE THREAD

**Issue by jyrkka** [Viglino/ol-ext#607]
When map contains WebGLPointsLaye with hit detection disabled we get lots of exception in the console such as this:

<code>
Uncaught AssertionError: Assertion failed. See https://openlayers.org/en/v6.5.0/doc/errors/#66 for details.
    at new AssertionError (webpack-internal:///./node_modules/ol/AssertionError.js:38:24)
    at assert (webpack-internal:///./node_modules/ol/asserts.js:14:15)
    at WebGLPointsLayerRenderer.forEachFeatureAtCoordinate (webpack-internal:///./node_modules/ol/renderer/webgl/PointsLayer.js:520:68)
    at CompositeMapRenderer.MapRenderer.forEachFeatureAtCoordinate (webpack-internal:///./node_modules/ol/renderer/Map.js:135:48)
    at Map.PluggableMap.forEachFeatureAtPixel (webpack-internal:///./node_modules/ol/PluggableMap.js:507:31)
</code>

When using EdiBar-component at least Offset, Transform and Select (when clicking map point where there is not feature), above exception is thrown. Also Hover interaction throws the same.

With the Hover-component I tried using the layers-option to filter out all other layers but it didn't seem to have any effect on the result. What is interesting is that with the OpenLayers Select-interactions I get the same, but when using the layers-option the problem goes away. 

Comparing the Openlayers Select and your Hover components i can see one difference that could cause this. 

In here (https://github.com/Viglino/ol-ext/blob/master/src/interaction/Hover.js) line 120, when calling forEachFeatureAtPixel-function of the map, should the options also contain layerFilter-value? 

Code example: https://codesandbox.io/s/openlayers-webglpointlayer-hitdetection-9gjib?file=/index.js

**Comment by Viglino** [comment]
You're right. The test layer function is at the wrong place....
I fixed it in the last commit.
