### ISSUE TITLE
SelectMulti - example

### ISSUE THREAD

**Issue by Bear4** [Viglino/ol-ext#754]
http://viglino.github.io/ol-ext/examples/control/map.control.selectmulti.html
Example with select control doesn't work.

   map.control.selectmulti.html:170 
        
```
    Uncaught ReferenceError: $ is not defined
    at ol.control.SelectMulti.<anonymous> (map.control.selectmulti.html:170:5)
    at ol.control.SelectMulti.n.dispatchEvent (Target.js:114:11)
    at ol.control.SelectMulti.doSelect (ol-ext.js:14773:8)
    at ol.control.SelectPopup.<anonymous> (ol-ext.js:14809:32)
```

**Comment by Bear4** [comment]
Ok. thanks!
