### ISSUE TITLE
Error with minified lib 4.0.4

### ISSUE THREAD

**Issue by Gaetanbrl** [Viglino/ol-ext#901]
Hi !

I had change a OpenLayer map to OL 7.x and migrate ol-ext to last compliant version **v4.0.4**.

But i get an `error with ol.filter.Mask` class : 

```
Uncaught TypeError: Class constructor V cannot be invoked without 'new'
    at ol.filter.Base [as constructor] (ol-ext.min.js:9:317173)
    at new ol.filter.Mask (ol-ext.min.js:9:318893)
```

After replace minified `ol-ext.min.js` by `ol-ext.min.js` from `/dist` zip release fodler it works !

**Comment by Viglino** [comment]
Maybe there is an issue when minifying...
You can use the ol-ext.js instead...

**Comment by Gaetanbrl** [comment]
@Viglino yes as explained, `ol-ext.js` works fine ! :)
This is not a big issue.
